[package]
name = "tipping"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "tipping"
crate-type = ["cdylib"]

[dependencies]
fancy-regex = "0.13.0"
pyo3 = "0.19.0"
tipping-rs = "0.1.4"
